# リリース準備をするワークフロー
name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to release (e.g., patch, minor, major, 1.2.3)"
        required: true
        default: "patch"

jobs:
  prepare-release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Bump version and changelog
        run: |
          VERSION=$(npm version ${{ github.event.inputs.version }} --no-git-tag-version | tail -n 1)
          BRANCH="release/$VERSION"

          npx conventional-changelog -p angular -i CHANGELOG.md -s
          git checkout -b "$BRANCH"
          git add package*.json CHANGELOG.md
          git commit -m "chore(release): $VERSION"
          git push origin "$BRANCH"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          title: "chore(release): ${{ github.event.inputs.version }}"
          body: "This PR prepares the release by bumping the version and updating the changelog."
